name: ego-hand
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mediapipe==0.10.35
      - opencv-contrib-python==5.0.0.93
      - numpy==2.2.6
      - PyYAML==6.0.3
      - python-dateutil==2.9.0.post0
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - scipy==1.15.3
      - trimesh==4.7.4
      - chumpy==0.70
      - typeguard==4.4.4
variables:
  PYTHONNOUSERSITE: "1"
